// Code generated by resourcegen scaffolding.
// This file is a starting point; implement the backend for real behavior.

package rule

import (
	"sgroups.io/sgroups-k8s-api/internal/registry/generic"
	registryoptions "sgroups.io/sgroups-k8s-api/internal/registry/options"
	"sgroups.io/sgroups-k8s-api/pkg/apis/sgroups/v1alpha1"
	"sgroups.io/sgroups-k8s-api/pkg/client"
)

// NewStorage creates a Rule storage backed by gRPC.
func NewStorage(c *client.Client, opts registryoptions.StorageOptions) *generic.Storage[*v1alpha1.Rule, *v1alpha1.RuleList] {
	return generic.NewStorage(
		&backend{client: c},
		opts,
		&ruleStrategy{},
		func() *v1alpha1.Rule { return &v1alpha1.Rule{} },
		func() *v1alpha1.RuleList { return &v1alpha1.RuleList{} },
		"rule",
	)
}
