// Code generated by resourcegen. DO NOT EDIT.

package apiserver

import (
	"k8s.io/apiserver/pkg/registry/rest"
	"sgroups.io/sgroups-k8s-api/internal/registry/addressgroup"
	registryoptions "sgroups.io/sgroups-k8s-api/internal/registry/options"
	"sgroups.io/sgroups-k8s-api/internal/registry/tenant"
	"sgroups.io/sgroups-k8s-api/pkg/client"
)

func buildStorageMap(grpcClient *client.Client, opts registryoptions.StorageOptions) map[string]map[string]rest.Storage {
	return map[string]map[string]rest.Storage{
		"v1alpha1": {
			"addressgroups": addressgroup.NewStorage(grpcClient, opts),
			"tenants":       tenant.NewStorage(grpcClient, opts),
		},
	}
}
