// Code generated by resourcegen scaffolding.
// This file is a starting point; implement the backend for real behavior.

package host

import (
	"sgroups.io/sgroups-k8s-api/internal/registry/generic"
	registryoptions "sgroups.io/sgroups-k8s-api/internal/registry/options"
	"sgroups.io/sgroups-k8s-api/pkg/apis/sgroups/v1alpha1"
	"sgroups.io/sgroups-k8s-api/pkg/client"
)

// NewStorage creates a Host storage backed by gRPC.
func NewStorage(c *client.Client, opts registryoptions.StorageOptions) *generic.Storage[*v1alpha1.Host, *v1alpha1.HostList] {
	return generic.NewStorage(
		&backend{client: c},
		opts,
		nil,
		func() *v1alpha1.Host { return &v1alpha1.Host{} },
		func() *v1alpha1.HostList { return &v1alpha1.HostList{} },
		"host",
	)
}
