// Code generated by resourcegen. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

// KnownTypes returns all registered runtime objects for this API group.
func KnownTypes() []runtime.Object {
	return []runtime.Object{
		&AddressGroup{},
		&AddressGroupList{},
		&HostBinding{},
		&HostBindingList{},
		&Host{},
		&HostList{},
		&Network{},
		&NetworkList{},
		&Tenant{},
		&TenantList{},
	}
}
