apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: sgroups
    includeSelectors: false

resources:
  - namespace.yaml
  - rbac.yaml
  - certificates.yaml
  - deployment.yaml
  - mock-backend.yaml    # remove when switching to the real backend
  - apiservice.yaml

configMapGenerator:
  - name: sgroups-apiserver-config
    namespace: sgroups-system
    files:
      - config.yaml=apiserver-config.yaml

generatorOptions:
  disableNameSuffixHash: true
