apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sgroups-tenant-editor
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["sgroups.io"]
    resources: ["tenants"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sgroups-tenant-viewer
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: ["sgroups.io"]
    resources: ["tenants"]
    verbs: ["get", "list", "watch"]
