// Code generated by resourcegen scaffolding.
// This file is a starting point; implement the backend for real behavior.

package network

import (
	"sgroups.io/sgroups-k8s-api/internal/registry/generic"
	registryoptions "sgroups.io/sgroups-k8s-api/internal/registry/options"
	"sgroups.io/sgroups-k8s-api/pkg/apis/sgroups/v1alpha1"
	"sgroups.io/sgroups-k8s-api/pkg/client"
)

// NewStorage creates a Network storage backed by gRPC.
func NewStorage(c *client.Client, opts registryoptions.StorageOptions) *generic.Storage[*v1alpha1.Network, *v1alpha1.NetworkList] {
	return generic.NewStorage(
		&backend{client: c},
		opts,
		nil,
		func() *v1alpha1.Network { return &v1alpha1.Network{} },
		func() *v1alpha1.NetworkList { return &v1alpha1.NetworkList{} },
		"network",
	)
}
