// Code generated by resourcegen scaffolding.
// This file is a starting point; implement the backend for real behavior.

package service

import (
	"sgroups.io/sgroups-k8s-api/internal/registry/generic"
	registryoptions "sgroups.io/sgroups-k8s-api/internal/registry/options"
	"sgroups.io/sgroups-k8s-api/pkg/apis/sgroups/v1alpha1"
	"sgroups.io/sgroups-k8s-api/pkg/client"
)

// NewStorage creates a Service storage backed by gRPC.
func NewStorage(c *client.Client, opts registryoptions.StorageOptions) *generic.Storage[*v1alpha1.Service, *v1alpha1.ServiceList] {
	return generic.NewStorage(
		&backend{client: c},
		opts,
		&serviceStrategy{},
		func() *v1alpha1.Service { return &v1alpha1.Service{} },
		func() *v1alpha1.ServiceList { return &v1alpha1.ServiceList{} },
		"service",
	)
}
