// Code generated by resourcegen. DO NOT EDIT.

package client

import (
	"google.golang.org/grpc"

	sgroupsv1 "github.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1"
)

func newClient(conn *grpc.ClientConn) *Client {
	return &Client{
		Conn:          conn,
		AddressGroups: sgroupsv1.NewSGroupsAddressGroupsAPIClient(conn),
		HostBindings:  sgroupsv1.NewSGroupsHostBindingAPIClient(conn),
		Hosts:         sgroupsv1.NewSGroupsHostsAPIClient(conn),
		Networks:      sgroupsv1.NewSGroupsNetworksAPIClient(conn),
		Namespaces:    sgroupsv1.NewSGroupsNamespaceAPIClient(conn),
	}
}
