// Code generated by resourcegen. DO NOT EDIT.

package client

import (
	"google.golang.org/grpc"

	sgroupsv1 "github.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1"
)

func newClient(conn *grpc.ClientConn) *Client {
	return &Client{
		Conn:            conn,
		AddressGroups:   sgroupsv1.NewSGroupsAddressGroupsAPIClient(conn),
		HostBindings:    sgroupsv1.NewSGroupsHostBindingAPIClient(conn),
		Hosts:           sgroupsv1.NewSGroupsHostsAPIClient(conn),
		NetworkBindings: sgroupsv1.NewSGroupsNetworkBindingAPIClient(conn),
		Networks:        sgroupsv1.NewSGroupsNetworksAPIClient(conn),
		Rules:           sgroupsv1.NewSGroupsRulesAPIClient(conn),
		ServiceBindings: sgroupsv1.NewSGroupsServiceBindingAPIClient(conn),
		Services:        sgroupsv1.NewSGroupsServicesAPIClient(conn),
		Namespaces:      sgroupsv1.NewSGroupsNamespaceAPIClient(conn),
	}
}
