// Code generated by resourcegen scaffolding.
// This file is a starting point; implement conversion tests.

package convert

import (
	"testing"

	"sgroups.io/sgroups-k8s-api/pkg/apis/sgroups/v1alpha1"
)

func TestNetworkBindingConversion(t *testing.T) {
	t.Skip("TODO: implement NetworkBinding conversion test")
	_ = NetworkBindingFromProto(NetworkBindingToProto(&v1alpha1.NetworkBinding{}))
}
